version: '3.8'

services:
  pretix:
    image: 'pretix/standalone:stable'
    container_name: pretix.service
    restart: always 
    depends_on:
      - db
      - redis
    ports:
      - '8345:80'
    volumes:
      - /var/pretix-data:/data
      - /etc/pretix:/etc/pretix
      - /var/run/redis:/var/run/redis
    sysctls:
      - net.core.somaxconn=4096
    networks:
      - stack_network

  db:
    image: postgres:latest
    container_name: pretix.db
    restart: always
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
      - POSTGRES_DB=pretix
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/pgdata:/var/lib/postgresql/data/pgdata
    ports: 
      - '5432:5432'
    networks:
      - stack_network
  
  redis:
    image: redis:latest
    container_name: pretix.redis
    restart: always
    networks:
      - stack_network

networks: 
  stack_network:
    external: false